### ISSUE TITLE
As a user I would like to create expense recordings

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#100]
Expense recording is a stripped down version of a travel expense. For this reason, there won't be any new functionality, just a different screen with fewer fields. [Figma](https://www.figma.com/file/7HZJK17nvKpicBO3SuRWt7/Expense-%26-Pay2?node-id=1533%3A92941)
**Requirements**
- [x] Should be able to add "Expense title" (similar to Travel expense's "Reason for travel")
- [x] Should be able to add "Period" (similar to Travel expense's "Travel period")
    - [x] Should only be able to select start and end date, NOT time
- [x] Should be able to add Mileage
- [x] Should be able to add expenses
- [x] Should be able to add cost distribution
- [x] Should be able to add attachments
- [x] Should be able to see a summary
- [x] Should be able to confirm and send

**Comment by tormodAase** [comment]
Ready for test (32287)

**Comment by tormodAase** [comment]
@ntorsen

**Comment by tormodAase** [comment]
Found an issue with not being able to add time to travel expenses, building a new version now

**Comment by ntorsen** [comment]
### Result from testing on build 32287
✅ Should be able to add "Expense title" (similar to Travel expense's "Reason for travel")
✅ Should be able to add "Period" (similar to Travel expense's "Travel period")
✅ Should only be able to select start and end date, NOT time 
✅ Should be able to add Mileage
🐛Should be able to add expenses
✅Should be able to add cost distribution
✅ Should be able to add attachments
✅ Should be able to see a summary
✅ Should be able to confirm and send

**Remarks:**
- Expense recording should not show time (only date) according to requirements, and it is in fact not possible to select time either. But then we probably should not show time when date is selected in Travel period, New expense and in Mileage?

![image](https://user-images.githubusercontent.com/89014017/170679530-1dcedc4a-aca4-41ce-b736-0fdf78c4082d.png)

- Not allowed to select transportation type "Work journey", "Commuter", "Work journey >200 km", "Commuter, >200km", "El car, Work journey > 200 km", "El car, Commuter", "El car, Commuter > 200 km", "El car, Work journey" and "Conversion of km from old syst" in Mileage. Get message: "Error: No entry in V_T706F". The other types are drafted successfully to SAP.

![image](https://user-images.githubusercontent.com/89014017/170681985-0dac539b-2d44-43aa-8160-19172f10b3ee.png)

- Tried to add different types of expenses; Hotel, Taxi, Course fee, Public transportation, but get message "Error: Failed to read property 'Amount' at offset '81'. So therefore not able to add an expense. 

![image](https://user-images.githubusercontent.com/89014017/170679447-e45d4270-f588-4370-9969-21ae16c3a8e2.png)

- Adding a description for new expense, keyboard does not disappear when clicking on "return" (as I would expect it to). Clicking on return moves you further down the description box for further writing. Have to click outside keyboard in order to make it go away.

![image](https://user-images.githubusercontent.com/89014017/170682115-d75bbc7c-518e-4b1c-9454-bcf09c37765f.png)

- Not possible to click on expense recordings that has been confirmed and sent. Will not show summary. Can only click on expense recordings that is 'in draft'.

- Expense recording can be "Confirmed and send", and will get status "Approved" just like travel expense does. But I'm not able to find my expense recordings in PR05 in SAP. Where should I go to verify that these in fact has been drafted successfully to SAP? @mglendrange 

@tormodAase

**Comment by tormodAase** [comment]
> Expense recording should not show time (only date) according to requirements, and it is in fact not possible to select time either. But then we probably should not show time when date is selected in Travel period, New expense and in Mileage?

As far as I know, only the "Period" field for expense recordings should not show time, or let the user be able to select time. But maybe @mglendrange could enlighten us

> Not allowed to select transportation type "Work journey", "Commuter", "Work journey >200 km", "Commuter, >200km", "El car, Work journey > 200 km", "El car, Commuter", "El car, Commuter > 200 km", "El car, Work journey" and "Conversion of km from old syst" in Mileage. Get message: "Error: No entry in V_T706F". The other types are drafted successfully to SAP.

@konrad-drygas Should unselectable transportation types be displayed to the user?

> Tried to add different types of expenses; Hotel, Taxi, Course fee, Public transportation, but get message "Error: Failed to read property 'Amount' at offset '81'. So therefore not able to add an expense.

@konrad-drygas has something changed related to expenses?

> Adding a description for new expense, keyboard does not disappear when clicking on "return" (as I would expect it to). Clicking on return moves you further down the description box for further writing. Have to click outside keyboard in order to make it go away.

I'll look into if there's a different keyboard I can display. Description is currently a multiline field though, so there should probably be some way for you to go to next line.

> Not possible to click on expense recordings that has been confirmed and sent. Will not show summary. Can only click on expense recordings that is 'in draft'.

Fixed in latest build 32297

**Comment by mglendrange** [comment]
@ntorsen PR04 is used for expense recordings in SAP.

@tormodAase @ntorsen I only think it is on the expense recording that there should be no time, and that expense items and mileage should work just as with a travel. I will need to verify in the existing app, but not able to log in there now. Will check again on monday :)

**Comment by tormodAase** [comment]
@ntorsen creating a new build now that would let you add expense to expense recording. Please note that there are many issues with expenses that we haven't fixed yet. For example I don't think the description field should be there at all. But in the next build you should be able to create an expense and see if that works as expected for expense recordings

**Comment by ntorsen** [comment]
@mglendrange PR04 guided me to 'Oversikt over ukerapporter', and I could not find any familiar expense recordings there. But I found a another way to get to expense recordings, by going into PR05 > add ansattnummer > Gå til > Utgiftsrefusjon.
![image](https://user-images.githubusercontent.com/89014017/170703433-0596aa70-a030-4a61-9853-b453a15b65ae.png)
![image](https://user-images.githubusercontent.com/89014017/170704076-20fe63bd-5d5b-49c2-a2ef-922f877a6257.png)

**Comment by konrad-drygas** [comment]
> > Not allowed to select transportation type "Work journey", "Commuter", "Work journey >200 km", "Commuter, >200km", "El car, Work journey > 200 km", "El car, Commuter", "El car, Commuter > 200 km", "El car, Work journey" and "Conversion of km from old syst" in Mileage. Get message: "Error: No entry in V_T706F". The other types are drafted successfully to SAP.
> 
> @konrad-drygas Should unselectable transportation types be displayed to the user?


@tormodAase - it's also not possible to use these types in the back-end system. I think the configuration of Q97 isn't correct/complete. The HR department needs to fix it. However, if some types should not be available for employees, I'd like to get a way to distinguish which types are okay. 

How does it look in the old app? I can't check it now, because I can't log in. :(

**Comment by konrad-drygas** [comment]
>  PR04 guided me to 'Oversikt over ukerapporter', and I could not find any familiar expense recordings there. But I found a another way to get to expense recordings, by going into PR05 > add ansattnummer > Gå til > Utgiftsrefusjon.

Yeah, PR04 is not for Expense recording. You can use ZR05. This is a custom transactional code (T-Code), so it only exists here in Equinor.

**Comment by tormodAase** [comment]
@ntorsen Build 32302 should be ready soon, it should let you add expense to expense recordings

**Comment by ntorsen** [comment]
**Able to add expense to expense recording on build 32302** 💪
- Verified that expense recording is listed in ZR05, with correct expense types

![image](https://user-images.githubusercontent.com/89014017/170720244-52bee960-5b90-4b76-b3e9-f2659630ba65.png)

Also:
- Able to click on expense recordings that have been approved/confirmed and sent
- Title in summary has been updated

**Some feedbacks:**
- Description of expense will not show in summary

![image](https://user-images.githubusercontent.com/89014017/170719670-21fb25f6-9b9f-4316-b850-154f0199fa40.png)
 
- In ZR05 in SAP, expense recording is listed with Refusjonsbeløp zero 

![image](https://user-images.githubusercontent.com/89014017/170719935-fd6b9365-8439-4057-b974-e5cad504a10a.png)

- If you simulate expense recording in ZR05, Refusjonsbeløp should have been listed as 9 568,-

![image](https://user-images.githubusercontent.com/89014017/170721544-3458b377-c5af-4cfe-9ff1-d79fac3f0b62.png)

@tormodAase

**Comment by mglendrange** [comment]
@ntorsen @tormodAase just checked and can conclude that it should not be possible to select a time when creating either a mileage allowance or an expense item. This is applies to both travel expenses and expense recordings.

**Comment by tormodAase** [comment]
@ntorsen We will probably show something other than description in the expense summary, since description won't be a standard field for expenses. I have created a new issue for time in expenses as mentioned by Magnus https://github.com/equinor/mad-expense-and-pay-app/issues/106

As for the Refusjonsbeløp zero, maybe it's a bug for @konrad-drygas to look into

**Comment by ntorsen** [comment]
@konrad-drygas Refusjonsbeløp is zero for newly created travel expenses as well
