### ISSUE TITLE
As a user I would like to add a comment to my travel expense and expense recording

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#102]
**Requirements**
- [x] Enable the user to add a comment in the TravelDetails/ExpenseRecordingDetails tab
- [x] Sync the comment to SAP
- [x] Read the comment from SAP if the user opens a travel / expense recording from SAP
- [x] Display the comment in the summary tab

**Comment by tormodAase** [comment]
32464 soon available for test!

**Comment by tormodAase** [comment]
PS: I forgot to display the comment in the summary tab, but everything else should work as expected

**Comment by ntorsen** [comment]
All of the requirements (except display comment in summary tab) is working as it should 👍

But I want to add a comment here beyond the requirements.. How many characters is allowed to put into this comment field? It did not seem to have a limit, but from past experience I know that SAP can have a problem if there is to much text (that it will not show all of the text).

Also there seem to be a limit for the 'Reason for travel' field, so maybe instead of the error message it shows the user now, we could instead say how many characters a user is able to input?

![image](https://user-images.githubusercontent.com/89014017/172641674-d478ebbf-074a-42bf-9a08-3683c01b0b62.png)

And if you put in a sentence like the one in the screenshot for reason for travel field, it will move the trash can icon:
![image](https://user-images.githubusercontent.com/89014017/172641957-ce4887a8-53fd-43dc-9825-dcc0f845c9db.png)
 
 @tormodAase

**Comment by tormodAase** [comment]
Input size should probably be handled better in general in the whole app. I have created a new issue #127

Comments should now also be in the summary page. I'm creating a test build soon

**Comment by tormodAase** [comment]
Build 32496 should be ready after lunch

**Comment by tormodAase** [comment]
Magnus confirmed Comments don't have a max length

**Comment by ntorsen** [comment]
### Tested on build 32496. Working very good 💪
- Able to add a comment in the TravelDetails/ExpenseRecordingDetails tab
- Able to read comment from SAP
- Able to see the displayed comment in the summary tab

To clarify, I put in 700 characters in the comment field for both TravelDetails and ExpenseRecordingDetails, and it did not have any problems either in app nor in SAP:

![image](https://user-images.githubusercontent.com/89014017/173081333-bfa4a0f1-e84a-4261-9a19-6aa2f4d310db.png)

![image](https://user-images.githubusercontent.com/89014017/173081240-537329b1-696d-484d-84e3-4679ec37ac48.png)

@tormodAase

**Comment by konrad-drygas** [comment]
@tormodAase @ntorsen 

I don't know if it's still important, but "Reason for travel" can contain up to 59 characters.

Regarding comments, yes, we may assume there is no limit. Theoretically, there is a limit based on the database and configuration of the whole system. However, I typed in over 21 thousand characters and it was fine.
