### ISSUE TITLE
Calendar List should scroll to relevant month

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#152]

**Comment by tormodAase** [comment]
Fix soon available for test (32832)

**Comment by SegarJJ** [comment]
Seems that not all use of the date picker in the app allows for the 'focus on the travel dates' fix to be experienced.

- [ ] Add expense to a travel
- [ ] Add mileage to a travel
- [ ] Add another destination to a travel

Otherwise, clicking on an existing item with a date set, does focus the calendar properly.

**Comment by SegarJJ** [comment]
opened this item to carry over any remaining low priority work.....

- [ ] https://github.com/equinor/mad-expense-and-pay-app/issues/157
