### ISSUE TITLE
The attachments should be synced to SAP

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#59]
When adding an attachment to the travel expense, it should be added to the draft in SAP. We can verify if this is working by closing the travel expense draft and reloading it from SAP. 

**Requirements**
- [x] Attachments should be sent as soon as the user has added them
- [x] The user should be able to see the progress
- [x] The attachments should be visible for the user when they open a draft from SAP
- [x] The user should not be able to add attachments unless a draft has already been made in SAP (because we need the trip id)

**Comment by konrad-drygas** [comment]
@tormodAase It is working like that. If you send an attachment via an OData, and everything is okay, the attachment is saved in the backend. Since then, you can retrieve it.

**Comment by tormodAase** [comment]
@konrad-drygas Yeah this card is for the frontend. Currently we don't sent attachments to SAP.

**Comment by tormodAase** [comment]
As a result of this feature, we also remove the ability to rename and delete attachments, as it's not possible to name attachments nor delete them in SAP

**Comment by tormodAase** [comment]
@ntorsen Ready for test, Build 32132 is soon available in testflight

**Comment by ntorsen** [comment]
**Result from testing on build 32132 (Q97)**

_**What is working good:**_ ✅
* Draft is successfully synced to SAP after filling out all mandatory fields (reason for travel, travel period, destinations, cost allocation)
* Able to add attachments after all mandatory field are filled out, and draft is successfully synced to SAP

![image](https://user-images.githubusercontent.com/89014017/169009559-e4b4664d-93f4-47d5-b0be-ec54227d1830.png)

* Travel expense has status 'In draft'. and you are able to view attachments from both app and in SAP

![image](https://user-images.githubusercontent.com/89014017/169009968-2198b614-aaf6-47c3-837a-e30aa3796454.png)

![image](https://user-images.githubusercontent.com/89014017/169010019-ced90f9f-8fa3-4660-a839-17a235e92426.png)

* Attachments are sent to SAP as soon as they are added in app, and they are visible for the user when they open draft from SAP
![image](https://user-images.githubusercontent.com/89014017/169010046-10b8b44a-10d7-4c46-bfcb-d0cdbb1571cd.png)

* It is not possible to add attachments unless a draft has already been made in SAP (because trip id is needed). Very good that the icon on the right hand side tells user what is missing in the travel expense in order to make a draft 🏆

![image](https://user-images.githubusercontent.com/89014017/169010471-9577a5be-88f1-435b-9931-44651df33f22.png)

![image](https://user-images.githubusercontent.com/89014017/169010489-a1f95bd8-9ad3-4c6f-a7e3-5298a5be37d9.png)

_**What is not working yet:**_ ⚠
* From requirements stated above it says that user should be able to see the progress. I'm not able to do so as it is not possible to 'Confirm and send' travel expense. It is always 'In draft'. 

@tormodAase

**Comment by ntorsen** [comment]
@tormodAase Also worth mentioning: I'm not able to click on thumbnail to see the attachment in app when in draft. Does not work from clicking on thumbnail from Attachments tab and in Summary

**Comment by tormodAase** [comment]
@ntorsen Hey, we have not implemented the ability to look at thumbnails yet. There's an issue for that here https://github.com/equinor/mad-expense-and-pay-app/issues/52

As for progress, there should be an icon on the right side of the attachment. If it's the grey icon, it's uploading. If it's the green icon, it successfully got uploaded to SAP.
If it's a red icon, something went wrong.
I don't have an image of the red icon diplaying cuz it's hard for me to reproduce in development mode.


![Image](https://user-images.githubusercontent.com/22524448/169029180-9f4a6602-db20-4990-b231-177ab6fc9540.png)
![Image](https://user-images.githubusercontent.com/22524448/169029242-acfd53b9-10cb-457a-9bae-6e0849223056.png)

**Comment by ntorsen** [comment]
@tormodAase okay good 👍
I have images of the red and green icon from comment above. But then it is working as intended😊

**Comment by tormodAase** [comment]
@ntorsen Is this considered ready for release then?

**Comment by tormodAase** [comment]
Nevermind, saw it was moved. Great
