### ISSUE TITLE
Triptype and relation to private accommodation

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#74]
Type trip: there are different types of Business trips, Busin. trip w/o comp.priv.acc (J), Business trip (A), Business trip, private acc. (B), Business trip over 28 days (D), Business trip (Room/barracks) (H). I see some of them have private accommodation in them, is it so that if they have this wording that they cannot or have to use Private accommodation in the Refunds section? If a Business trip type does not allow for private accommodation, then would we disable that section?

Also, does the choice of trip type affect which expenses to use and not?

**Comment by ntorsen** [comment]
Hi @mglendrange, is this something that you can look into? 
Let me know if what I wrote is unclear or not informative enough

**Comment by mglendrange** [comment]
@ntorsen I see that in the current app there is no such logic, but there is at least a correlation between selected trip type and what expenses you can use. E.g if you select "Business trip, private acc.", then you are not able to register an Hotel receipt on the travel. As far as meal deductions and private accommodation is conserned, I haven't registered any correlation between trip type and what you can select here. That does not mean that there is no such correlation though, but I have not encountered it so far while testing.

In an ideal world the front end would reflect the real options available to the user, but if we are to implement this the configuration data should come from an API endpoint. As of today there is no such endpoint, and implementing one would not be straight forward, as it would need quite a bit of debugging in order to detect how SAP handles these checks today. Given where we are both time and cost wise I think it is unlikely that the customer would want to implement this. At least prior to go-live.

cc: @tormodAase

**Comment by mglendrange** [comment]
@ntorsen closing this issue
